In [3]:
import numpy as np

In [5]:
arr_1d=np.arange(1,13)#arrange is use to make an array in a given range
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
even_arr=np.arange(2,13,2)# to find the even num in a given arays
print(even_arr)


[ 2  4  6  8 10 12]


In [10]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [11]:
arr_2d=arr_1d.reshape(2,6)#reshape is used to convert 1d arays into 2d or 3d arays
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
arr_3d=arr_1d.reshape(4,3)
print(arr_3d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr_3d=np.arange(1,13).reshape(2,3,2)#here is no of arays u want to create from given arays,rows,columns(2,3,2)
print(arr_3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
arr_3d=arr_1d.reshape(3,2,2)#same as above
print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [16]:
arr_3d.ravel()#(ravel)to convert multi-dimensions arrays into 1 d arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
arr_3d.flatten()#(flatten) to convert multi d arrays into 1d arays


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
arr_2d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])