In [1]:
import numpy as np

In [2]:
arr_1d= np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_1d.ndim

1

In [5]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
type(arr_2d)

numpy.ndarray

In [7]:
arr_2d.ndim #for dimensions of array

2

In [8]:
arr_2d.size #for size of array

8