In [1]:
import numpy as np



In [16]:
arr_2d=np.array([[1,2,3,4],[2,3,4,5]])


In [3]:
arr_2d.shape # forno of rows and columns

(2, 4)

In [4]:
arr_2d.dtype # to check data type

dtype('int32')

In [5]:
mx_1s=np.array([[[1,1,1],[1,1,1],[1,1,1]]])# to convert ones matrix
print(mx_1s)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [6]:
mx_1s=np.ones(5) #direct function to create ones matrix 
print(mx_1s)

[1. 1. 1. 1. 1.]


In [7]:
mx_1s.dtype

dtype('float64')

In [8]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
mx_1s.shape

(3, 4)

In [10]:
    mx_1s=np.ones((3,4),dtype=int) # by using shift + tab key
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
mx_0s=np.zeros((4,5),dtype=int) #to create zeroes matrix
print(mx_0s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
mx_0s=np.zeros((4,5),dtype=bool) #to convert into bool data type
print(mx_0s)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [13]:
mx_0s=np.zeros((4,5),dtype=str) #to convert into bool data type
print(mx_0s)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [14]:
em_mx=np.empty((3,3))# to create a empty matruix
print(em_mx)

[[4.67296746e-307 1.69121096e-306 1.24610994e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]
