In [1]:
import numpy as np


In [21]:
arr1=np.arange(1,10).reshape(3,3) #create two arrays of shape(3,4)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr1+arr2


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
np.add(arr1,arr2) # to add two matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
np.subtract(arr1,arr2) # to subtarct two matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
np.divide(arr1,arr2) #to divide

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.multiply(arr1,arr2) # to multiply

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [27]:
arr1 @ arr2 # (@) multiply row element of first matrix to column elements of second matrix


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [28]:
arr1.dot(arr2) #same as above

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])